version: '3'

services:
  api-solid-03-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=apirest03
